### ISSUE TITLE
Profile better sig konstigt 

### ISSUE THREAD

**Issue by Gustav-Rixon** [Gustav-Rixon/d0018e#3]
[Thu Nov 26 17:30:22.461871 2020] [wsgi:error] [pid 1583710] [remote 82.209.143.227:21390] ERROR:my_flask_app:Exception on /profile [GET]
[Thu Nov 26 17:30:22.462055 2020] [wsgi:error] [pid 1583710] [remote 82.209.143.227:21390] Traceback (most recent call last):
[Thu Nov 26 17:30:22.462077 2020] [wsgi:error] [pid 1583710] [remote 82.209.143.227:21390]   File "/home/flask_app/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
[Thu Nov 26 17:30:22.462089 2020] [wsgi:error] [pid 1583710] [remote 82.209.143.227:21390]     response = self.full_dispatch_request()
[Thu Nov 26 17:30:22.462099 2020] [wsgi:error] [pid 1583710] [remote 82.209.143.227:21390]   File "/home/flask_app/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
[Thu Nov 26 17:30:22.462110 2020] [wsgi:error] [pid 1583710] [remote 82.209.143.227:21390]     rv = self.handle_user_exception(e)
[Thu Nov 26 17:30:22.462120 2020] [wsgi:error] [pid 1583710] [remote 82.209.143.227:21390]   File "/home/flask_app/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
[Thu Nov 26 17:30:22.462131 2020] [wsgi:error] [pid 1583710] [remote 82.209.143.227:21390]     reraise(exc_type, exc_value, tb)
[Thu Nov 26 17:30:22.462141 2020] [wsgi:error] [pid 1583710] [remote 82.209.143.227:21390]   File "/home/flask_app/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
[Thu Nov 26 17:30:22.462151 2020] [wsgi:error] [pid 1583710] [remote 82.209.143.227:21390]     raise value
[Thu Nov 26 17:30:22.462161 2020] [wsgi:error] [pid 1583710] [remote 82.209.143.227:21390]   File "/home/flask_app/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
[Thu Nov 26 17:30:22.462171 2020] [wsgi:error] [pid 1583710] [remote 82.209.143.227:21390]     rv = self.dispatch_request()
[Thu Nov 26 17:30:22.462182 2020] [wsgi:error] [pid 1583710] [remote 82.209.143.227:21390]   File "/home/flask_app/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
[Thu Nov 26 17:30:22.462192 2020] [wsgi:error] [pid 1583710] [remote 82.209.143.227:21390]     return self.view_functions[rule.endpoint](**req.view_args)
[Thu Nov 26 17:30:22.462203 2020] [wsgi:error] [pid 1583710] [remote 82.209.143.227:21390]   File "/home/flask_app/ExampleFlask/my_flask_app.py", line 95, in profile
[Thu Nov 26 17:30:22.462251 2020] [wsgi:error] [pid 1583710] [remote 82.209.143.227:21390]     cursor.execute('SELECT * FROM Customers WHERE id = % s', (session['id'],))
[Thu Nov 26 17:30:22.462264 2020] [wsgi:error] [pid 1583710] [remote 82.209.143.227:21390]   File "/home/flask_app/venv/lib/python3.8/site-packages/werkzeug/local.py", line 377, in <lambda>
[Thu Nov 26 17:30:22.462273 2020] [wsgi:error] [pid 1583710] [remote 82.209.143.227:21390]     __getitem__ = lambda x, i: x._get_current_object()[i]
[Thu Nov 26 17:30:22.462282 2020] [wsgi:error] [pid 1583710] [remote 82.209.143.227:21390]   File "/home/flask_app/venv/lib/python3.8/site-packages/flask/sessions.py", line 84, in __getitem__
[Thu Nov 26 17:30:22.462291 2020] [wsgi:error] [pid 1583710] [remote 82.209.143.227:21390]     return super(SecureCookieSession, self).__getitem__(key)
[Thu Nov 26 17:30:22.462300 2020] [wsgi:error] [pid 1583710] [remote 82.209.143.227:21390] KeyError: 'id'

**Comment by Gustav-Rixon** [comment]
Förmodligen något med MySQL requesten cursor.execute('SELECT * FROM Customers WHERE email = % s AND password = % s', (email, password,)) borde nog vara "SELECT * FROM Customers"

**Comment by Gustav-Rixon** [comment]
fixed it was an issue on how we requested information from the server
